### ISSUE TITLE
Main "tiles" menu does not load on a fresh .deb installation

### ISSUE THREAD

**Issue by ptesavol** [spaceify/spaceify#2]
On a fresh installation from .deb packages on Ubuntu 14.04 Desktop (no virtual machine), Spaceify clients see a web page with the contents "Welcome This is the default page of Spaceify Core Web Server" instead of the main "tiles" menu at edge.spaceify.net. Spaceify works otherwise normally, bigscreen opens with a direct URL and pictureviewer spacelet works as expected.

**Comment by jovepsala** [comment]
When Spaceify's own DHCP server was removed there remained a reference to it in the index template. This is now removed and edge.spaceify.net is displayed correctly.
